// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvlxefdinynlmgopjvtz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2bHhlZmRpbnlubG1nb3BqdnR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzM5MzcsImV4cCI6MjA2NDcwOTkzN30.cd1OIUSvYS-4KGALSsyh7qNbc68qz3C8Rlvm9Ovzzig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);