// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zoashnlvqoawggpjfyed.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvYXNobmx2cW9hd2dncGpmeWVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1ODcwNDUsImV4cCI6MjA2MTE2MzA0NX0.QnrJVe6ujjvmXxuvQk611o1K9opQ8PNcO7evvKrDd6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);